
// DO NOT EDIT THIS BLOCK BELOW=== Parameters starts ===
// PLEASE DO NOT EDIT THIS FILE

import com.cloudbees.flowpdf.StepParameters

class ExecuteQueriesParameters {
    /**
    * Label: Database Type, type: select
    */
    String database
    /**
    * Label: Database server, type: entry
    */
    String server
    /**
    * Label: Database port, type: entry
    */
    String port
    /**
    * Label: Database credentials, type: credential
    */
    String credential
    /**
    * Label: Database name, type: entry
    */
    String databaseName
    /**
    * Label: Database Properties, type: entry
    */
    String properties
    /**
    * Label: SQL query, type: textarea
    */
    String sql_queries

    static ExecuteQueriesParameters initParameters(StepParameters sp) {
        ExecuteQueriesParameters parameters = new ExecuteQueriesParameters()

        def database = sp.getRequiredParameter('database').value
        parameters.database = database
        def server = sp.getRequiredParameter('server').value
        parameters.server = server
        def port = sp.getRequiredParameter('port').value
        parameters.port = port
        def credential = sp.getRequiredParameter('credential').value
        parameters.credential = credential
        def databaseName = sp.getRequiredParameter('databaseName').value
        parameters.databaseName = databaseName
        def properties = sp.getParameter('properties').value
        parameters.properties = properties
        def sql_queries = sp.getRequiredParameter('sql_queries').value
        parameters.sql_queries = sql_queries

        return parameters
    }
}
// DO NOT EDIT THIS BLOCK ABOVE ^^^=== Parameters ends, checksum: 1bacf84799b95288bbecf03933cc28d0 ===
