
// DO NOT EDIT THIS BLOCK BELOW=== Parameters starts ===
// PLEASE DO NOT EDIT THIS FILE

import com.cloudbees.flowpdf.StepParameters

class ExecuteQueryParameters {
    /**
    * Label: Database Type, type: select
    */
    String database
    /**
    * Label: Database server, type: entry
    */
    String server
    /**
    * Label: Database port, type: entry
    */
    String port
    /**
    * Label: Database credentials, type: credential
    */
    String credential
    /**
    * Label: Database name, type: entry
    */
    String databaseName
    /**
    * Label: Database Properties, type: entry
    */
    String properties
    /**
    * Label: SQL query, type: entry
    */
    String sql_query

    static ExecuteQueryParameters initParameters(StepParameters sp) {
        ExecuteQueryParameters parameters = new ExecuteQueryParameters()

        def database = sp.getRequiredParameter('database').value
        parameters.database = database
        def server = sp.getRequiredParameter('server').value
        parameters.server = server
        def port = sp.getRequiredParameter('port').value
        parameters.port = port
        def credential = sp.getRequiredParameter('credential').value
        parameters.credential = credential
        def databaseName = sp.getRequiredParameter('databaseName').value
        parameters.databaseName = databaseName
        def properties = sp.getParameter('properties').value
        parameters.properties = properties
        def sql_query = sp.getRequiredParameter('sql_query').value
        parameters.sql_query = sql_query

        return parameters
    }
}
// DO NOT EDIT THIS BLOCK ABOVE ^^^=== Parameters ends, checksum: 3146915e02d35d73e90f04cda4834e6e ===
